### ISSUE TITLE
Scoring Rubric Task List

### ISSUE THREAD

**Issue by jgagne** [evelynjamesmcmullen/pugweb#1]
# Theme Style
## Scoring Rubric Task List

10 tasks, `10 points` each; with 1 extra credit task

### Essentials

`20 points`

- [x] Use of essential metadata
  - Use of the HTML5 character encoding meta tag (this should be the first meta tag inside your `<head>` element [to ensure special characters display properly])
    - For example: `<meta charset="utf-8">`
      - See [The Road to HTML 5: character encoding](https://blog.whatwg.org/the-road-to-html-5-character-encoding)
  - Use of a mobile-friendly, viewport meta tag
    - For example: `<meta name="viewport" content="width=device-width, initial-scale=1">`
  - Use of an external stylesheet
      - For example: `<link rel="stylesheet" href="css/main.css">`
  - Use of a meaningful `title` element
    - `<title>Easy Fish Tacos Recipe</title>`
  - Use of a meaningful `description` meta tag
    - For example: `<meta name="description" content="Get the feeling of authentic handmade fish tacos at home with ease!">`
  - Use of canonical link to reference original or preferred content source
    - For example: `<link rel="canonical" href="https://www.spendwithpennies.com/fish-tacos-recipe-onion-slaw/>`
    - Note: If the original content source is your own, include the url of your webpage (`https://username.github.io/repo/`)
  - Use of an author meta tag
    - For example: `<meta name="author" content="Firstname Lastname">`
- [x] Use of essential markup best practices
  - Use of lowercase alphabet for all markup, style, and file/folder names (also `class`, `id`, and file/folder names should not include spaces, instead use a hyphen `-` or an underscore `_` instead of a space).
    - For example: `<section id="ingredients-for-sauce">` not `<section id="Ingredients for Sauce">`; `main.css` not `Main.CSS`
  - Use of semantic section and grouping elements (`h1`–`h6` , `section`, `p`, etc.) and semantic text-level elements (`strong`, `em`, `time`, etc.) for content
    - See HTML5 Doctor’s [HTML5 Element Index](http://html5doctor.com/#glossary)
    - See also [If you’ve ever had doubts about how to mark up subheadings](https://medium.com/@barvysta/if-youve-ever-had-doubts-about-how-to-mark-up-subheadings-220cbe97c361)

### Navigation

`10 points`

- [x] Use of navigation (`nav`) with a unordered list (`ul`) of links (`a`) to navigate from page to page
  - For example: [Semantic navigation with the nav element](http://html5doctor.com/nav-element/)
    - Use of custom color for default blue hyperlinks states
        - For example: `a {color: #f90;} a:hover, a:focus {color: #f30;}`
     - Also, consider a "Back to Top" or "Back to Menu" link at the bottom of the page

### Design

`30 points`

- [x] Use of a cohesive and accessible color palette for typography, borders, background colors, and imagery
  - Use of [Accessible Colors](http://accessible-colors.com) — test the color contrast ratio of your webpage meets the Web Content Accessibility Guidelines (WCAG) 2.1.
  - If it fails — make it pass `#greenisgood`
- [x] Use of web safe fonts (with the proper generic font family fallback)
  - See [Web safe fonts](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Web_safe_fonts)
  - See also [CSS font stacks](http://www.cssfontstack.com) for fallbacks
- [x] Use of a mobile first (single-column layout for small screens) design approach and a responsive layout for wider screens using Bootstrap or custom media queries

### Validation

`20 points`

Resolve all errors; warnings are ok. (But try to resolve warnings if possible)

- [x] [Validate HTML](https://validator.w3.org)
- [x] [Validate CSS](http://jigsaw.w3.org/css-validator/)

### Git Organized

`20 points`

- [x] Repo should contain only essential files/folders:
  - `index.html` (root-level document)
  - `css` (a folder containing an external stylesheet)
    - For example: `main.css`
  - `img` (a folder containing images)
    - For example: `fish-tacos.jpg`
  - `wip` ([or by any other name, but please keep it short or abbreviated] a folder containing tests, work in progress, etc.)
  - `README.md`
    - Update this file with a heading (title) and paragraph (description)
    - Markdown [basic](http://daringfireball.net/projects/markdown/basics) and [dingus](http://daringfireball.net/projects/markdown/dingus)
      - See [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
- [x] Add a [description and url](https://i.imgur.com/CexeWBQ.gif) to your GitHub repo
  - For example: [https://github.com/jgagne/recipe-markup/](https://github.com/jgagne/recipe-markup/)
    - A tasty HTML & CSS recipe.[ https://jgagne.github.io/recipe-markup/](https://jgagne.github.io/recipe-markup/)

### Extra Credit

`10 points`

- [ ] Use of [Bootstrap](https://getbootstrap.com) for foundational layout (grid/breakpoints) styles and `main.css` for custom styles
